name: ZigStar MG24 HW Zigbee
device: EFR32MG24A420F1536IM48
base_project: src/zigbee_ncp
sdk: "gecko_sdk:4.4.4"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: ncp-uart-hw
  dynamic: ["ezsp_version"]
  baudrate: 115200

configuration:
  SL_RAIL_UTIL_PTI_MODE: RAIL_PTI_MODE_DISABLED
  SL_IOSTREAM_USART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_USART_VCOM_FLOW_CONTROL_TYPE: usartHwFlowControlCtsAndRts

c_defines:
  SL_IOSTREAM_USART_VCOM_PERIPHERAL: USART0
  SL_IOSTREAM_USART_VCOM_PERIPHERAL_NO: 0

  SL_IOSTREAM_USART_VCOM_TX_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_TX_PIN:  4

  SL_IOSTREAM_USART_VCOM_RX_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_RX_PIN:  5

  SL_IOSTREAM_USART_VCOM_CTS_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_CTS_PIN:  3

  SL_IOSTREAM_USART_VCOM_RTS_PORT: gpioPortB
  SL_IOSTREAM_USART_VCOM_RTS_PIN:  2

  SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE: 64
  
  EMBER_APS_UNICAST_MESSAGE_COUNT: 32
  EMBER_BROADCAST_TABLE_SIZE: 64
  EMBER_NEIGHBOR_TABLE_SIZE: 26
  EMBER_SOURCE_ROUTE_TABLE_SIZE: 254

  SL_DEVICE_INIT_HFXO_CTUNE: 92
